// src/data/voice-references.ts
// References are curated constants, not user input. No sanitization needed here.
// If references ever include client-submitted text, apply wrapUntrustedData.
//
// Provenance:
//   Real, converted: Patterson, Starikov, Dang, Miranda (Alex's actual sent messages)
//   System-drafted: Carlsbad Flamenco, Eilynn Memorial, Cuban Birthday, Sparse Cocktail
//     (generated by Spiral, validated through 17-test quality gate)
//
// Dollar amounts replaced with [QUOTED_PRICE]. Pricing-adjacent language neutralized.
// Contact blocks stripped (pipeline adds its own).

export type VoiceReferenceType =
  | "premium_wedding"
  | "sparse_social"
  | "corporate"
  | "platform_budget_mismatch"
  | "cultural_heritage"
  | "urgent_emotional"
  | "sourced_cultural_duo"
  | "minimal_detail";

export interface VoiceReference {
  name: string;
  type: VoiceReferenceType;
  text: string;
  active: boolean;
}

export const VOICE_REFERENCES: VoiceReference[] = [
  // --- Active references (ordered weakest-to-strongest; strongest last for recency bias) ---

  {
    // Real, converted. GigSalad budget mismatch. Maximum compression (~50 words).
    name: "Miranda",
    type: "platform_budget_mismatch",
    text: `Hi Miranda,

I've performed at Lomas Santa Fe before for a Mexican themed dinner, soft Spanish guitar is exactly right. Solo guitar fills a small space beautifully without overwhelming conversation.

Solo Spanish Guitar [QUOTED_PRICE] (2 hours)
If your budget is firm, I can do a focused 90-minute set.

I'm available Friday, want me to hold it?`,
    active: true,
  },

  {
    // Real, converted. Sparse social lead. Demonstrated understanding from absence.
    name: "Starikov",
    type: "sparse_social",
    text: `Hi Roman,

You found a guitarist, not a DJ or a playlist which tells me you're after a specific feel for this evening.

Three hours gives you room to breathe: music already playing when guests arrive, something warm underneath the conversation through dinner, and space to lift the energy when the moment calls for it. I've played private events in La Jolla for years, including The Lodge at Torrey Pines, Estancia La Jolla, Village courtyards, and Spanish guitar fits this neighborhood like nothing else.

Quick question: who's the birthday for? Knowing that helps me shape the evening.

Solo Spanish Guitar [QUOTED_PRICE] 3 hours | Professional sound, setup/breakdown, repertoire calibrated to your evening

I'm available March 21. Just say the word and I'll hold it.`,
    active: true,
  },

  {
    // System-drafted, validated. Cultural heritage, gift-giver frame, flamenco trio.
    name: "Carlsbad Flamenco",
    type: "cultural_heritage",
    text: `Your mother left Sevilla at 25 and built a life and a family on this side of the ocean. Now she's turning 80, surrounded by sixty people, half of whom crossed that ocean to be there. The flamenco isn't entertainment. It's the sound of where she comes from.

I've been performing flamenco in San Diego for over 30 years, and I work with artists who understand that when the room is full of Sevillanos, you don't perform at them, you ignite with them.

Here's how this unfolds: Guitar and cajón through dinner, warm, present, the kind of music that makes conversation easier. Then the dancer steps in, and with half the room from Sevilla, you won't need to encourage anyone. The palmas will come naturally. Your mother will be sitting in the middle of a juerga she didn't know she was getting.

You're the one making sure she hears the music of home on her 80th birthday. That's a beautiful gift.

Flamenco Trio, [QUOTED_PRICE] for three hours, with the dancer featured during the final hour.`,
    active: true,
  },

  {
    // System-drafted, validated. GigSalad, sparse cocktail, differentiation from nothing.
    name: "Sparse Cocktail",
    type: "minimal_detail",
    text: `Hi Cyrus,

Saturday evening in July, 150 people arriving in waves, and the guitar already working the room before the crowd fills in. The first twenty minutes are the real test: too quiet and the silence is awkward, too present and people feel watched. Getting that calibration right from the first guest to the last is what separates a musician from a playlist.

You decided 150 people deserved live music. That changes the whole evening.

For a cocktail setting this size outdoors, I play Spanish classical, Latin, and bossa nova on nylon string, warm enough to carry across the space, quiet enough that every conversation feels easy. I'm fully self-contained with battery-powered sound, no venue coordination, no setup on your end.

Solo Spanish Guitar, [QUOTED_PRICE], 1.5 hours. I arrive early and have the sound dialed before your first guest walks in.

Want me to hold July 18th?`,
    active: true,
  },

  {
    // Real, converted. Premium wedding-adjacent. Strongest voice ceiling.
    // LAST in active set for recency bias (Anthropic best practice).
    name: "Patterson",
    type: "premium_wedding",
    text: `Hi Joseph,

The night before the wedding, both families at Torrey Pines watching the sunset over the Pacific, that's the moment where everyone stops being "the groom's side" and "the bride's side" and just becomes family. Spanish guitar is perfect for that: warm enough to fill the silences, quiet enough that real conversation happens.

I've performed at the Lodge many times and know how to work both the private room and patio seamlessly. For a four-hour evening like this, I typically shape the music in phases with lighter and ambient during cocktails on the patio as the sun sets, present but unobtrusive through dinner, then warmer and more intimate as the evening winds down and toasts happen.

I'm fully self-contained with professional sound. I arrive early, set up quietly, and handle everything.

Solo Spanish Guitar - [QUOTED_PRICE]
4 hours (5:30-9:30) | Professional sound, phased repertoire, complete setup/breakdown

I'm available February 13th. Want me to hold it?`,
    active: true,
  },

  // --- Inactive references (corpus-only, available for future activation) ---

  {
    // Real, converted. Corporate nonprofit. Voice is notably simpler/more direct
    // than other references. "Would be happy to provide" is vendor-speak that
    // contradicts voice rules. Inactive to avoid confusing the model.
    name: "Dang",
    type: "corporate",
    text: `Hi Jessica,

Thanks for contacting me and congratulations on your plans!

I am available on that date and would be happy to provide the music for your event. My rate for the time requested is [QUOTED_PRICE] and I can offer a community event adjustment. Price includes event insurance and sound. Please let me know if that could work.`,
    active: false,
  },

  {
    // System-drafted, validated. Memorial/grief. Calibration language, no cinematic opening.
    // Inactive initially; activate when memorial-lead override is validated.
    name: "Eilynn Memorial",
    type: "urgent_emotional",
    text: `Eilynn, I'm so sorry for your loss. The fact that you're making sure live music is part of this says a lot about how much this person meant. I play classical and Spanish guitar, present enough to hold the room together during the quiet moments, gentle enough to never compete with what people are feeling. I bring everything needed for indoor, professional sound, completely self-contained, and I arrive early to be set up before the first guest walks in. I'm available tomorrow morning. [QUOTED_PRICE] for one hour. Want me to lock it in tonight?`,
    active: false,
  },

  {
    // System-drafted, validated. Cuban cultural duo, sourced (Pacific Flow coordinating).
    // Inactive initially; overlaps with Carlsbad Flamenco for cultural coverage.
    name: "Cuban Birthday",
    type: "sourced_cultural_duo",
    text: `Saturday night, 9 PM, thirty guests, and Cuban music, that's not background, that's the moment the birthday becomes a party. You decided this celebration deserved the real thing, and that choice is going to show the second the first rhythm hits.

For events like yours, most clients go with a Cuban duo, guitar and percussion delivering authentic son cubano with enough energy to get people moving while staying intimate for thirty guests. They're fully self-contained with professional sound, so no equipment on your end.

[QUOTED_PRICE] for the two hours. I'm available March 14th, want me to hold the date while you finalize?`,
    active: false,
  },
];
